name: Django Unit Tests  # More descriptive name

on:
  push:
    branches:
      - master   # Run only on pushes to the master branch 

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    # Use the latest checkout action version
      - name: Set up Python 
        uses: actions/setup-python@v4  # Use setup-python action
        with:
          python-version: '3.x'       # Specify the python version for your project
      - name: Install Dependencies
        run: pip install -r requirements.txt 
      - name: Run Django Unit Tests
        run: python manage.py test

