# Generated by Django 5.0.6 on 2024-05-19 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_following"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="following",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="following",
            constraint=models.UniqueConstraint(
                fields=("user", "followed_user"), name="unique_followers"
            ),
        ),
    ]
