# Generated by Django 5.0.4 on 2024-04-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_id_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
