# Generated by Django 5.0.4 on 2024-04-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(null=True, upload_to='listing_images'),
        ),
    ]
