# Generated by Django 5.0.4 on 2024-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
