name: Basic Django Test

on: 
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Django
        run: pip install Django
      - name: Run Django Tests (Assuming Project Name is 'myproject')
        working-directory: Lecture7/airline  # Update if your Django project is in a different location
        run: python manage.py test
